### ISSUE TITLE
Allow php 8 in SymfonyBridge

### ISSUE THREAD

**Issue by garak** [SimpleBus/SimpleBus#108]
I can provide a PR, if needed.

**Comment by garak** [comment]
Sorry, I just noticed that php 8 is already allowed, but only in dev-master.
Is there an ETA for a new release?

**Comment by pascaldevink** [comment]
@cmodijk @ruudk any word on when simplebus/symfony-bridge will get a new tagged release?

**Comment by ruudk** [comment]
I'll try to do that this week.

**Comment by ruudk** [comment]
I just tagged [v6.0.0-RC1](https://github.com/SimpleBus/SimpleBus/tree/v6.0.0-RC1). Please test it out and let us know if it's working properly.

**Comment by ruudk** [comment]
https://github.com/SimpleBus/SimpleBus/releases/tag/v6.0.0 is now released.
