### ISSUE TITLE
TypeError with Doctrine\Common\Persistence\ManagerRegistry

### ISSUE THREAD

**Issue by samijnih** [SimpleBus/SimpleBus#109]
Hello :)

Happy valentine's day!

I'm currently facing this error below using `"simple-bus/doctrine-orm-bridge": "^5.1"`.

```
TypeError: SimpleBus\DoctrineORMBridge\MessageBus\WrapsMessageHandlingInTransaction::__construct(): Argument #1 ($managerRegistry) must be of type Doctrine\Common\Persistence\ManagerRegistry, Doctrine\Bundle\DoctrineBundle\Registry given, called in /var/www/html/var/test/cache/ContainerMEBxOdm/getSimpleBus_DoctrineOrmBridge_WrapsNextCommandInTransactionService.php on line 23
```

> vendor/doctrine/doctrine-bundle/Resources/config/dbal.xml
![image](https://user-images.githubusercontent.com/10528754/107885342-f6b68180-6ef9-11eb-918e-e30af484c0d7.png)

The class seems not to exist anymore in Doctrine and I think it's now `Doctrine\Persistence\ManagerRegistry`

So I've tried to change the use statement inside of `WrapsMessageHandlingInTransaction` to use that interface and works properly

```
use Doctrine\Persistence\ManagerRegistry;
```

- PHP 8.0.1
- Symfony 5.2.3
- Doctrine Dbal 2.12.1
- Doctrine Orm 2.8.1
- Doctrine Persistence 2.1.0
- Doctrine Common 3.1.1
- Doctrine Bundle 2.2.3
- SimpleBus Doctrine Orm Bridge 5.1.0

Do you think it's a good fix without risk of any breaking changes?

Have a nice evening :)

**Comment by ruudk** [comment]
This is already fixed in `main`. Could you try to install that and see if it works for you?

**Comment by ruudk** [comment]
https://github.com/SimpleBus/SimpleBus/tree/v6.0.0-RC1

**Comment by samijnih** [comment]
Hello :)

Tested and it works pretty well. Thanks!

**Comment by ruudk** [comment]
@samijnih Thanks for getting back to us. https://github.com/SimpleBus/SimpleBus/releases/tag/v6.0.0 is now released.
