### ISSUE TITLE
View differences between versions

### ISSUE THREAD

**Issue by gjuric** [SimpleBus/SimpleBus#111]
Could you make it possible to view changes between releases?

Trying to open https://github.com/SimpleBus/message-bus/compare/v6.0.0...v3.1.0 I get a message:

> There isn’t anything to compare.
> v6.0.0 and v3.1.0 are entirely different commit histories. 

In case of this repository, there are only Tags for v6.

**Comment by ruudk** [comment]
I'm sorry about this. We've switched to a different method of monorepo splitting that causes this to happen.

Not sure how to compare them now. 

Maybe @cmodijk has an idea?

**Comment by cmodijk** [comment]
No, sorry this is because of our split methode which creaties different root commit trees.

**Comment by gjuric** [comment]
Not even in the monorepo going forward?

It would be nice to at least add the main change in the Githubs Release section.

**Comment by cmodijk** [comment]
In the monorepo you can view the diff between versions but only from the point we imported the other repositories.

**Comment by cmodijk** [comment]
And if you clone it on you own computer and use a tool like [SourceTree](https://www.sourcetreeapp.com/) you can view the diff.

<img width="560" alt="Schermafbeelding 2021-02-26 om 19 52 00" src="https://user-images.githubusercontent.com/771041/109342449-29eb0000-786c-11eb-89d6-1cfe4c9ab991.png">

**Comment by gjuric** [comment]
Thank you.
