### ISSUE TITLE
Are you sure that min stability of SimpleBus/asynchronous-bundle should be dev?

### ISSUE THREAD

**Issue by tonykulaga** [SimpleBus/SimpleBus#116]
I got a composer conflict saying that SimpleBus/asynchronous-bundle:^6.0 min stability is not compatible with my project min stability level.
https://github.com/SimpleBus/asynchronous-bundle/blob/v6.0.0/composer.json#L54

Is it supposed to be like that?

**Comment by ruudk** [comment]
This should not have any impact on you as a user of this library.

I checked and Symfony does the same: https://github.com/symfony/proxy-manager-bridge/blob/fd6bb40190b1719abbe831be09adf38e0744d5f5/composer.json#L33

What error are you getting?
