### ISSUE TITLE
Disable read only repositories issues

### ISSUE THREAD

**Issue by caciobanu** [SimpleBus/SimpleBus#18]
Hi guys!

Maybe we should disable the possibility for all read only repositories and update the README.md with a link to the main repo ?

Do you need help to move issues, if that is a necessary step?

**Comment by cmodijk** [comment]
> Maybe we should disable the possibility for all read only repositories and update the README.md with a link to the main repo ?

Merged your pull requests thanks!

> Do you need help to move issues, if that is a necessary step?

We merged or closed all pull requests today. For issues we try to close them and then close the issues setting inside the last repositories.

**Comment by cmodijk** [comment]
But we can get some help in getting the tests running for the Mono repository https://github.com/SimpleBus/SimpleBus/pull/17

**Comment by caciobanu** [comment]
Looking into it now.
