### ISSUE TITLE
Decide what to do with the BernardBundleBridge

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#24]
A lot of tests are failing for `BernardBundleBridge` and the Bernard project seems to be at a stand still we need to decide if we still want to keep supporting it. 

- [ ] Remove code from mono repository #29
- [x] Mark project as deprecated 
- [x] Archive project on github

**Comment by ruudk** [comment]
At my company we decided to drop Bernard for a new project we started because it's not very active ☠️ . We choose Enqueue as our queue and created a tiny wrapper around SimpleBus Asynchronous. So I'm ok with stopping maintenance for the package.

**Comment by ruudk** [comment]
Not sure how many people are actually using it. @lakiboy first started this and moved away from it.

**Comment by lakiboy** [comment]
Yep, I'm not using it any more. As I said in some other thread, there is no point in maintaining it as BernardPHP is more or less dead.

**Comment by cmodijk** [comment]
So what should we do? We can remove it from the mono repository and archive the old repository right?

**Comment by lakiboy** [comment]
Fine by me whatever path you take. I guess the old repo will still be available for download (via composer) for old projects.

**Comment by cmodijk** [comment]
Should we also remove the [docs](http://docs.simplebus.io/en/latest/Bundles/BernardBundleBridge.html) or let those there for a while?

**Comment by lakiboy** [comment]
There is a _doc_ directory within the repo. If it is cleaner for you to remove the docs, I'm fine with that.

**Comment by cmodijk** [comment]
That is true i updated my pull request.
