### ISSUE TITLE
Move the code to src directory

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#26]
At the moment al the code is in the root of the project maybe we should move this to the `src` directory?

**Comment by caciobanu** [comment]
We can do this but it will look a little strange having **src/Component/MessageBus/src**. How about dropping src from each component and just use the top src ? Something like Symfony does.

**Comment by caciobanu** [comment]
Maybe we should do a composer install & unit/functional testing for each component separately ? This will help us drop the composer.json from the main repo and will provide faster feedback for each component. Also it will not required to sink composer.json from main repo with the ones from each component.

**Comment by cmodijk** [comment]
@ruudk and i started to try this but the problem then becomes that when you create a pull request that spans multiple packages then it wil install the wrong version.

**Comment by caciobanu** [comment]
Yes, it will fail but it can also be useful to catch api BC.

**Comment by cmodijk** [comment]
> Yes, it will fail but it can also be useful to catch api BC.

Yeah, that is true but the thing for me to go for the mono repository is that i need to make all packages compatible in 1 pull request. If we don't then we would need to merge a part of the code (which is the old situation with separate packages). Release that package then run the CI again to verify if that works.

**Comment by caciobanu** [comment]
Can i help with moving all code to from src/Component/MessageBus/src to src/Component/MessageBus/ ? But first, I think that you have to get #30 in.

**Comment by cmodijk** [comment]
We are moving to `packages/` in https://github.com/SimpleBus/SimpleBus/pull/88
