### ISSUE TITLE
Split SymfonyBridge in 3 different packages

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#27]
- DoctrineORMBridgeBundle
- CommandBusBundle
- EventBusBundle

Main reason to do this now is that we are already on the verge of creating a new major version and this allows us to force the `ProxyManager` dependecie for `DoctrineOrmBridgeBundle`.

**Comment by caciobanu** [comment]
+1. I think that it is a good idea to offer each bundle as a separate package.

**Comment by ruudk** [comment]
I'm 👎 on this. Let's not make this more complex.

**Comment by cmodijk** [comment]
The main reason behind this was that we don't need these checks. But i'm fine with leaving it as it is right now.  
https://github.com/SimpleBus/SimpleBus/blob/main/packages/symfony-bridge/src/RequiresOtherBundles.php#L14-L27
