### ISSUE TITLE
File could not be downloaded: failed to open stream:

### ISSUE THREAD

**Issue by PhPPgAdminBug** [SimpleBus/SimpleBus#31]
Symfony 4.0.2
Vagrant + Homestead
Windows 10 Pro

```
$ composer require simple-bus/simple-bus
The "http://packagist.org/p/provider-2015%249a252938f0616ff57cb6ed93c4ff6058afa50f095f82893466076a7cd61987ee.json" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did n
ot properly respond after a period of time, or established connection failed because connected host has failed to respond.

http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
....
```

So simple-bus package can not be installed

**Comment by caciobanu** [comment]
There is no simple-bus/simple-bus package registered on packagist. For symfony you should use 
simple-bus/symfony-bridge. Here you can find some documentation: http://docs.simplebus.io/en/latest/Symfony/getting-started.html

**Comment by cmodijk** [comment]
@caciobanu Is right there is no `simple-bus/simple-bus` the `composer.json` in the root is only for travis-ci
