### ISSUE TITLE
Missing recipe

### ISSUE THREAD

**Issue by garak** [SimpleBus/SimpleBus#35]
I tried to install `simple-bus/rabbitmq-bundle-bridge` with Symfony 4 (and so with Flex).

I'm getting this error:
> The child node "object_serializer_service_id" at path "simple_bus_asynchronous" must be configured. 

Likely, a recipe is missing here (maybe more than one).

**Comment by caciobanu** [comment]
You can fix that by installing **simple-bus/jms-serializer-bundle-bridge**.

Here is the documentation: http://docs.simplebus.io/en/latest/Guides/asynchronous-example.html

**Comment by caciobanu** [comment]
For now, simple-bus offer easy integration with jms/serializer. It is possible to use the Symfony serializer by making a custom simple-bus serializer. Docs on how to do that you can find here: http://docs.simplebus.io/en/latest/Components/Serialization.html.

**Comment by garak** [comment]
Apart from that, it's clear that some default is needed, otherwise you'll get the same error I've got (that's bad DX I guess).
A recipe would automatically add configuration, at least.
Otherwise, docs should suggest provided `SimpleBus\Serialization\NativeObjectSerializer` as default solution (and maybe jms as an alternate solution)

**Comment by cmodijk** [comment]
@garak @caciobanu The future of SimpleBus is also not sure at the moment Symfony added a new Messenger component which is inspired by SimpleBus. Maybe consider using there component instead? 

Details on how I see this will follow next week
* https://github.com/symfony/symfony-docs/pull/9901#issuecomment-396141594

**Comment by cmodijk** [comment]
This issue is already stale for several years so i'm closing it for now
