### ISSUE TITLE
Logging failed commands and requeue them

### ISSUE THREAD

**Issue by Koc** [SimpleBus/SimpleBus#36]
As I see from code of logging middleware
https://github.com/SimpleBus/SimpleBus/blob/master/Component/MessageBus/src/Logging/LoggingMiddleware.php
it doesn't logs failures until command handled. Is it expected behavior? How to log failed handling?

And non-relevant question: how it possible requeue message with some delay for later processing?

**Comment by caciobanu** [comment]
You can create your own logging middleware and do something like this:
```php
$this->logger->log($this->level, 'Started handling a message', ['message' => $message]);
try {
    $next($message);
} catch (\Exception $exception) {
    $this->logger->log(
        $this->level,
        'Error handling a message',
        [
            'message' => $message,
            'exception_message' => $exception->getMessage(),
        ]
    );
}
$this->logger->log($this->level, 'Finished handling a message', ['message' => $message]);
```

**Comment by Koc** [comment]
Thank, I know, but wondering why this not implemented out of the box?

Any idea about implementing requeue?

**Comment by caciobanu** [comment]
It should be possible to implement a re-queue system with the dead letter exchange and message TTL. Here is an article which might give you and idea on what you have to do: https://medium.com/@kiennguyen88/rabbitmq-delay-retry-schedule-with-dead-letter-exchange-31fb25a440fc.

**Comment by cmodijk** [comment]
This original issue is already stale for several years so i'm closing it for now
