### ISSUE TITLE
Allow to disable default FinishesHandlingMessageBeforeHandlingNext

### ISSUE THREAD

**Issue by scaytrase** [SimpleBus/SimpleBus#51]
in https://github.com/SimpleBus/SimpleBus/blob/c245f7afa98dcfdb9907e982373323974160744c/Bundle/SymfonyBridge/src/Resources/config/command_bus.yml#L52

FinishesHandlingMessageBeforeHandlingNext is enabled by default, which forces us to use "serialized" execution of the commands. But in our case we put commands to the bus inside the handler and expect that all handlers fail in chain if the inner handler fails, as well as we expect the command to be executed synchronously without delay, as the next code expect the modified state if command executed successfully.

Currently we have to disable this middleware using DI hacks with removing tags from service in order to achieve it.

**Comment by ruudk** [comment]
How does `FinishesHandlingMessageBeforeHandlingNext` forces the serialized commands? I'm not sure that's right.

**Comment by cmodijk** [comment]
This is expected behaviour

**Comment by cmodijk** [comment]
This is expected behaviour, if the command handler fails all commands that it has send should not be executed. It is developed like a transaction as the command fails all queries are reverted.

**Comment by scaytrase** [comment]
The part of the problem is not even with failing but with successful exectution. Calling `$bus->handle($command)` we expect that command would be handled after call finishes. For async execution we utilize delayed commands with other async tooling, like rabbitmq or jms job queue bundle.

Currently nested calls to `handle` leads to situations when different machanisms work in a different flows. I.e we call `$bus->handle($command)` and then the call `$eventDispatcher->dispatch($event)`. And listeners of this event a running at the point of time when `$command` is not handled yet (but the nature of the event expects it to be finished), so we have to disable this feature.

**Comment by scaytrase** [comment]
I understand that this is intentional behaviour and it suits most of the users. I just ask to make it configurable (with enabled by default, of course, to keep BC)

**Comment by cmodijk** [comment]
Sure, if you create a PR for this we can accept it.

**Comment by scaytrase** [comment]
@cmodijk I've introduced the simplest solution in #52

**Comment by cmodijk** [comment]
I'm closing this in favor of #52
