### ISSUE TITLE
[Request] - Lazy command handler middlewares

### ISSUE THREAD

**Issue by dadamssg** [SimpleBus/SimpleBus#60]
I've been wanting to use middlewares for command object validation and also for authorization. The problem is that their usage gets heavier and heavier as you add more since middlewares aren't lazily loaded. 

I've come up with a quick solution that works for me using a new decorator class and a compiler pass. It adds a bit of magic but i don't have to manually deal with defining chains of nested decorators in yaml. 

Basically, it [replaces the original](http://img.pandawhale.com/post-15882-Indiana-Jones-switching-idol-g-glxZ.gif) command handler with a new handler that contains a reference to the id of the original handler and id's of the middlewares you wish to apply to that specific handler. It will lazily instantiate the middlewares and original handler as needed.

Would anyone be interested in a me making a pull request? If it doesn't really align with the ideologies, no worries! Just throwing the idea out there. :)

[Here's a gist of what i've done.](https://gist.github.com/dadamssg/06f0c59a7fb35e910325#file-services-yml-L14)

**Comment by cmodijk** [comment]
This issue is already stale for several years so i'm closing it for now
