### ISSUE TITLE
Logging middleware before Transactional

### ISSUE THREAD

**Issue by acasademont** [SimpleBus/SimpleBus#62]
Hi Matthias!

I've been playing this week with the shiny new version and everything works like a charm, thanks! However, I was wondering why the Transactional Doctrine middleware is registered before the Logging middleware, I would prefer the transaction to be "as close as possible" to the real work done inside the command. If somehow the logging failed that would mean rolling back the transaction too, which is not desirable IMHO

> [2015-05-29 12:11:21] doctrine.DEBUG: "START TRANSACTION" [] []
> [2015-05-29 12:11:21] command_bus.DEBUG: Started handling a message {"message":"[object](Ulabox\Inventory\Application\Command\Sku\LinkWithProduct: {})"} []

```
array(5) {
  [0] =>
  string(71) "simple_bus.command_bus.finishes_command_before_handling_next_middleware"
  [1] =>
  string(56) "simple_bus.event_bus.handles_recorded_mesages_middleware"
  [2] =>
  string(64) "simple_bus.doctrine_orm_bridge.wraps_next_command_in_transaction"
  [3] =>
  string(41) "simple_bus.command_bus.logging_middleware"
  [4] =>
  string(62) "simple_bus.command_bus.delegates_to_message_handler_middleware"
}
```

Thanks!!

**Comment by cmodijk** [comment]
This issue is already stale for several years so i'm closing it for now
