### ISSUE TITLE
Dependency on CommandBus

### ISSUE THREAD

**Issue by gjuric** [SimpleBus/SimpleBus#63]
In order to use bundle "SimpleBusEventBusBundle" you also need to enable "SimpleBusCommandBusBundle"

What is the reason for this dependency? If it's needed, the docs on http://simplebus.github.io/SymfonyBridge/doc/event_bus_bundle.html should be updated that the bundle requires the SimpleBusCommandBusBundle as well.

**Comment by cmodijk** [comment]
I just want to get rid of these issues by splitting the bundle like it is mentioned in here https://github.com/SimpleBus/SimpleBus/issues/27 i'm closing this issue for now
