### ISSUE TITLE
Add support for multiple Entity Managers and connections

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#65]
Stated in this issue we need to be able to setup multiple Entity Manager names to flush
* https://github.com/SimpleBus/DoctrineORMBridge/issues/10

References
* https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/DoctrineOrmBridgeConfiguration.php
* https://github.com/SimpleBus/SymfonyBridge/blob/master/src/Resources/config/doctrine_orm_bridge.yml#L2-L7

**Comment by grachevko** [comment]
Any suggestions how to work with multiple connections/entity managers?

**Comment by cmodijk** [comment]
This issue is already stale for several years so i'm closing it for now
