### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Daredzik** [SimpleBus/SimpleBus#67]
According to this: https://github.com/SimpleBus/SymfonyBridge/issues/66 and this https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DoctrineOrmBridgeBundle.php#L41

DoctrineORMBridge should have require:
`proxy-manager-bridge`

Coz after update packages composer prompt:
` In order to use bundle \"DoctrineOrmBridgeBundle\" you need to require \"symfo  ", "!!    ny/proxy-manager-bridge\" package.`

**Comment by ruudk** [comment]
Found a way to transfer this issue.

**Comment by cmodijk** [comment]
This is a known issue and the reason i wanted to split the packages like mentioned in https://github.com/SimpleBus/SimpleBus/issues/27. I'm closing this issue as we know how we want to solve it but it just needs to be done one day.
