### ISSUE TITLE
Incorrect exception class catch in middleware - a short story why my consumer sometimes doesn't work

### ISSUE THREAD

**Issue by akondas** [SimpleBus/SimpleBus#72]
So in default configuration `FinishesHandlingMessageBeforeHandlingNext` middleware is enabled,  which assures us that the next message will be processed only after the current one has finished. Let us check how it looks like:

```php
$this->queue[] = $message;

        if (!$this->isHandling) {
            $this->isHandling = true;

            while ($message = array_shift($this->queue)) {
                try {
                    $next($message);
                } catch (Exception $exception) {
                    $this->isHandling = false;

                    throw $exception;
                }
            }

            $this->isHandling = false;
        }
```

The problem is that from PHP 7 `Exception` implement another interface `Throwable`. So when your consumer fails with (for example) TypeError then this middleware will badly mark the `isHandling` flag and put your next message on a queue.

In practice, this meant that from time to time messages were processed ultra-fast which made me very curious why, it turned out that these messages are not correctly processed, so I managed to get to this place.

Fixed in https://github.com/SimpleBus/SimpleBus/pull/71

**Comment by ruudk** [comment]
Great find. Fixed in https://github.com/SimpleBus/SimpleBus/pull/71
