### ISSUE TITLE
Add support for PHP 8

### ISSUE THREAD

**Issue by samijnih** [SimpleBus/SimpleBus#86]
Hello :rocket: 

I think all repositories here are not usable with PHP 8.

Composer tells me this:

![image](https://user-images.githubusercontent.com/10528754/101300035-7a862a80-3834-11eb-9daf-609fa8f6ef6b.png)

My composer.json requires PHP 8 and I'm using these versions:

```
"simple-bus/doctrine-orm-bridge": "^5.1",
"simple-bus/symfony-bridge": "^5.4",
```

Is it possible to add PHP 8 support?

Thank you :)

**Comment by ruudk** [comment]
Could you provide a PR to add support for PHP 8 (+ test it on CI)?

**Comment by samijnih** [comment]
#87

**Comment by cmodijk** [comment]
I'm closing this as https://github.com/SimpleBus/SimpleBus/pull/88 is close to getting merged
