### ISSUE TITLE
Automate split

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#90]
We now do a manual split from time to time to the different packages. We need to automated this and maybe Github actions can help us with that. 

The package that we use now is this
https://github.com/dflydev/git-subsplit

They also have a github webhook 
https://github.com/dflydev/dflydev-git-subsplit-github-webhook

**Comment by ruudk** [comment]
Done in https://github.com/SimpleBus/SimpleBus/commit/308f66399339a603d82daaec837dea04251a408b
