### ISSUE TITLE
Remove simple-bus/doctrine-orm-bridge test forks

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#91]
As discussed in https://github.com/SimpleBus/SimpleBus/pull/89#discussion_r540262301

https://github.com/SimpleBus/SimpleBus/blob/github-actions/packages/doctrine-orm-bridge/composer.json#L27-L40

**Comment by ruudk** [comment]
Done in https://github.com/SimpleBus/SimpleBus/pull/88
