### ISSUE TITLE
Remove jms-serializer-bundle-bridge ignore

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#92]
As discussed in https://github.com/SimpleBus/SimpleBus/pull/89#discussion_r540263781 when https://github.com/schmittjoh/JMSSerializerBundle/pull/819 is merged we can remove this case

https://github.com/SimpleBus/SimpleBus/blob/master/.github/workflows/tests.yaml#L62-L64

**Comment by ruudk** [comment]
Done.
