### ISSUE TITLE
Remove ocramius/proxy-manager fork

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SimpleBus#93]
As discussed in https://github.com/SimpleBus/SimpleBus/pull/89#discussion_r540264108 when https://github.com/Ocramius/ProxyManager/pull/628 is merged we can remove this

https://github.com/SimpleBus/SimpleBus/blob/master/packages/symfony-bridge/composer.json#L28-L34

**Comment by ruudk** [comment]
This is done.
